version: "3.9"

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
    expose:
      - 9200
    environment:
      - discovery.type=single-node
